rrt:
  max_iterations: 1000
  time_step: 0.1
  integration_time_limit: 1.0
  goal_sampling_bias: 0.5
  sampled_controls: 3

casadi_optimization:
  max_iterations: 100
  tol: 1e-6
  dt: 0.1
  n_steps: 10
